### ISSUE TITLE
Error when running container with detach=False

### ISSUE THREAD

**Issue by kiramt** [gabrieldemarmiesse/python-on-whales#112]
Thanks for making this package available, really useful! I'm trying to run a container in detached mode but I'm getting an error. As the same code works with detach=False I think this is likely a bug. Here's an example with detach=False and then detach=True:

```
>>> from python_on_whales import docker
>>> docker.run("tensorflow/tensorflow:2.3.2-gpu", gpus="all", detach=False)
''
>>> docker.run("tensorflow/tensorflow:2.3.2-gpu", gpus="all", detach=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pip/pipenvs/ml-UCgrIzmY/lib/python3.7/site-packages/python_on_whales/components/container.py", line 1625, in run
    return Container(self.client_config, run(full_cmd))
  File "/pip/pipenvs/ml-UCgrIzmY/lib/python3.7/site-packages/python_on_whales/components/container.py", line 338, in __init__
    super().__init__(client_config, "id", reference, is_immutable_id)
  File "/pip/pipenvs/ml-UCgrIzmY/lib/python3.7/site-packages/python_on_whales/client_config.py", line 149, in __init__
    self._fetch_and_parse_inspect_result(reference_or_id)
  File "/pip/pipenvs/ml-UCgrIzmY/lib/python3.7/site-packages/python_on_whales/client_config.py", line 204, in _fetch_and_parse_inspect_result
    return self._parse_json_object(json_object)
  File "/pip/pipenvs/ml-UCgrIzmY/lib/python3.7/site-packages/python_on_whales/components/container.py", line 355, in _parse_json_object
    return ContainerInspectResult.parse_obj(json_object)
  File "pydantic/main.py", line 520, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for ContainerInspectResult
HostConfig -> DeviceRequests -> 0 -> DeviceIDs
  none is not an allowed value (type=type_error.none.not_allowed)
HostConfig -> DeviceRequests -> 0 -> Capabilities -> 0
  str type expected (type=type_error.str)
```

**Comment by gabrieldemarmiesse** [comment]
Thank you for the bug report, it's great! I'll work on it this afternoon. This is a bug in the parsing of the json result. It's going to be quick to fix.

**Comment by kiramt** [comment]
Speedy fix! Thank you

**Comment by gabrieldemarmiesse** [comment]
The release is done, please update with `pip install --upgrade python-on-whales` and have fun!
