### ISSUE TITLE
ParsingError: missing ImageRootFS.layers field

### ISSUE THREAD

**Issue by KSmanis** [gabrieldemarmiesse/python-on-whales#162]
Building a Dockerfile having only a `scratch` layer fails due to the missing `ImageRootFS.layers` field:

```shell
$ cat Dockerfile 
FROM scratch
$ docker buildx build .
#1 [internal] load build definition from Dockerfile
#1 sha256:b19ad5a1751f726b260f534e1d3de4a59532e3a651aea6e375283e9fc3fc80cc
#1 transferring dockerfile: 50B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:cb562fd7e2ec07a3840a2c40f30e3e12af3e99ff7559d143c1ed611444828437
#2 transferring context: 2B done
#2 DONE 0.1s

#3 exporting to image
#3 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#3 writing image sha256:71de1148337f4d1845be01eb4caf15d78e4eb15a1ab96030809826698a5b7e30 done
#3 DONE 0.0s
$ pex python-on-whales==0.17.0 -- -c 'from python_on_whales import docker; docker.build(".")'
#1 [internal] load build definition from Dockerfile
#1 sha256:8272615fc5af2f67dd620e365814fe0c53ab0af6a1d4602be14b3233456af35d
#1 transferring dockerfile: 31B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:6a04879656730f99d6d88f3bcf00e7c638462cee6e1c0319a3e7d4224e8bd6eb
#2 transferring context: 2B done
#2 DONE 0.0s

#3 exporting to image
#3 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#3 writing image sha256:71de1148337f4d1845be01eb4caf15d78e4eb15a1ab96030809826698a5b7e30 done
#3 DONE 0.0s
Traceback (most recent call last):
  File "/home/socrates/.pex/installed_wheels/3319b96494d66102f31ee3f9b49bac3b6bbd0cd9/python_on_whales-0.17.0-py3-none-any.whl/python_on_whales/client_config.py", line 212, in _fetch_and_parse_inspect_result
    return self._parse_json_object(json_object)
  File "/home/socrates/.pex/installed_wheels/3319b96494d66102f31ee3f9b49bac3b6bbd0cd9/python_on_whales-0.17.0-py3-none-any.whl/python_on_whales/components/image/cli_wrapper.py", line 46, in _parse_json_object
    return ImageInspectResult.parse_obj(json_object)
  File "pydantic/main.py", line 572, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ImageInspectResult
RootFS -> Layers
  field required (type=value_error.missing)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/tmpng3_93uf/.bootstrap/pex/pex.py", line 483, in execute
    exit_value = self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/tmp/tmpng3_93uf/.bootstrap/pex/pex.py", line 400, in _wrap_coverage
    return runner(*args)
  File "/tmp/tmpng3_93uf/.bootstrap/pex/pex.py", line 431, in _wrap_profiling
    return runner(*args)
  File "/tmp/tmpng3_93uf/.bootstrap/pex/pex.py", line 542, in _execute
    return self.execute_interpreter()
  File "/tmp/tmpng3_93uf/.bootstrap/pex/pex.py", line 582, in execute_interpreter
    return self.execute_content("-c <cmd>", content, argv0="-c")
  File "/tmp/tmpng3_93uf/.bootstrap/pex/pex.py", line 649, in execute_content
    exec_function(ast, globals_map)
  File "/tmp/tmpng3_93uf/.bootstrap/pex/compatibility.py", line 93, in exec_function
    exec (ast, globals_map, locals_map)
  File "-c <cmd>", line 1, in <module>
  File "/home/socrates/.pex/installed_wheels/3319b96494d66102f31ee3f9b49bac3b6bbd0cd9/python_on_whales-0.17.0-py3-none-any.whl/python_on_whales/components/buildx/cli_wrapper.py", line 329, in build
    return docker_image.inspect(image_id)
  File "/home/socrates/.pex/installed_wheels/3319b96494d66102f31ee3f9b49bac3b6bbd0cd9/python_on_whales-0.17.0-py3-none-any.whl/python_on_whales/components/image/cli_wrapper.py", line 234, in inspect
    return Image(self.client_config, x)
  File "/home/socrates/.pex/installed_wheels/3319b96494d66102f31ee3f9b49bac3b6bbd0cd9/python_on_whales-0.17.0-py3-none-any.whl/python_on_whales/components/image/cli_wrapper.py", line 34, in __init__
    super().__init__(client_config, "id", reference, is_immutable_id)
  File "/home/socrates/.pex/installed_wheels/3319b96494d66102f31ee3f9b49bac3b6bbd0cd9/python_on_whales-0.17.0-py3-none-any.whl/python_on_whales/client_config.py", line 156, in __init__
    self._fetch_and_parse_inspect_result(reference_or_id)
  File "/home/socrates/.pex/installed_wheels/3319b96494d66102f31ee3f9b49bac3b6bbd0cd9/python_on_whales-0.17.0-py3-none-any.whl/python_on_whales/client_config.py", line 218, in _fetch_and_parse_inspect_result
    raise ParsingError(
python_on_whales.client_config.ParsingError: There was an error parsing the json response from the Docker daemon. 
This is a bug with python-on-whales itself. Please head to 
https://github.com/gabrieldemarmiesse/python-on-whales/issues 
and open an issue. You should copy this error message and 
the json response from the Docker daemon. The json response was put 
in /tmp/tmp5umqoql4.json because it's a bit too big to be printed 
on the screen. Make sure that there are no sensitive data in the 
json file before copying it in the github issue.
$ cat /tmp/tmp5umqoql4.json 
[
    {
        "Id": "sha256:71de1148337f4d1845be01eb4caf15d78e4eb15a1ab96030809826698a5b7e30",
        "RepoTags": [],
        "RepoDigests": [],
        "Parent": "",
        "Comment": "",
        "Created": "0001-01-01T00:00:00Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 0,
        "VirtualSize": 0,
        "GraphDriver": {
            "Data": null,
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers"
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

**Comment by gabrieldemarmiesse** [comment]
The bugfix version is out! Could you do `pip install --upgrade python-on-whales` and verify that it fixed your bug? Thank you very much!

**Comment by KSmanis** [comment]
Yep, all good. Thanks!
