### ISSUE TITLE
Error related to host net usge

### ISSUE THREAD

**Issue by BWibo** [gabrieldemarmiesse/python-on-whales#202]
I was trying to use the host net with a stack of mine and ran an error. Without using the host net, the stack can be deployed.
I am using:
``` console
> python3 -m pip show python_on_whales
Name: python-on-whales
Version: 0.20.2       
Summary: A Docker client for Python, designed to be fun and intuitive!
Home-page: UNKNOWN
Author: None
Author-email: None
License: MIT
Location: /home/bruno/.local/lib/python3.8/site-packages
Requires: tqdm, typer, pydantic, requests
Required-by:
```

```txt
There was an error parsing the json response from the Docker daemon.
This is a bug with python-on-whales itself. Please head to
https://github.com/gabrieldemarmiesse/python-on-whales/issues
and open an issue. You should copy this error message and
the json response from the Docker daemon. The json response was put
in /tmp/tmpqmi1g8fd.json because it's a bit too big to be printed
on the screen. Make sure that there are no sensitive data in the
json file before copying it in the github issue.
Traceback (most recent call last):
  File "/home/bruno/.local/lib/python3.8/site-packages/python_on_whales/client_config.py", line 214, in _fetch_and_parse_inspect_result
    return self._parse_json_object(json_object)
  File "/home/bruno/.local/lib/python3.8/site-packages/python_on_whales/components/task/cli_wrapper.py", line 32, in _parse_json_object
    return TaskInspectResult.parse_obj(json_object)
  File "pydantic/main.py", line 520, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TaskInspectResult
Spec -> Networks -> 0 -> Aliases
  field required (type=value_error.missing)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 700, in <module>
    master[0].status.state ) )
  File "/home/bruno/.local/lib/python3.8/site-packages/python_on_whales/components/task/cli_wrapper.py", line 84, in status
    return self._get_inspect_result().status
  File "/home/bruno/.local/lib/python3.8/site-packages/python_on_whales/components/task/cli_wrapper.py", line 36, in _get_inspect_result
    return super()._get_inspect_result()
  File "/home/bruno/.local/lib/python3.8/site-packages/python_on_whales/client_config.py", line 186, in _get_inspect_result
    self.reload()
  File "/home/bruno/.local/lib/python3.8/site-packages/python_on_whales/client_config.py", line 178, in reload
    self._fetch_and_parse_inspect_result(self._immutable_id)
  File "/home/bruno/.local/lib/python3.8/site-packages/python_on_whales/client_config.py", line 220, in _fetch_and_parse_inspect_result
    raise ParsingError(
python_on_whales.client_config.ParsingError: There was an error parsing the json response from the Docker daemon.
This is a bug with python-on-whales itself. Please head to
https://github.com/gabrieldemarmiesse/python-on-whales/issues
and open an issue. You should copy this error message and
the json response from the Docker daemon. The json response was put
in /tmp/tmpqmi1g8fd.json because it's a bit too big to be printed
on the screen. Make sure that there are no sensitive data in the
json file before copying it in the github issue.

```

Docker compose file I try to `stack deploy` with python on whales:

```yml
# https://github.com/compose-spec/compose-spec/blob/master/spec.md
version: "3.7"

secrets:
  aaa:
    name: aaa
    file: aaa

networks:
  hostnet:
    external: true
    name: host

services:
  # sunpot master -------------------------------------------------------------
  sunpot-master:
    image: aaa
    command: [
      "-h",aaa,
      "-p", aaa,
      "-d", aaa,
      "-u", "aaa,
      "-pw", aaa,
      "-t", "aaa",
      "-r", aaa
    ]
    secrets:
      - sunpotConfig
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "14"
          # memory: 128M
        reservations:
          cpus: "14"
         # memory: 64M
      restart_policy:
        condition: none
        # delay: 10s
        # max_attempts: 3
        # window: 120s
    networks:
      hostnet: {}
    extra_hosts:
      - "localhost:127.0.0.1"
```

Docker daemon json response: 

```json
[    
    {
        "ID": "z9382z35bvw0earue1tvorel5",
        "Version": {
            "Index": 3370
        },
        "CreatedAt": "2021-07-09T17:34:59.2002062Z",
        "UpdatedAt": "2021-07-09T17:35:00.676241Z",
        "Labels": {},
        "Spec": {
            "ContainerSpec": {
                "Image": "xxxx/xxxx:1.0.0@sha256:57d28200bd23ff51aab203498ffc6eb79a32be560f1d2ea102761eca29136abc",
                "Labels": {
                    "com.docker.stack.namespace": "xxxx"
                },
                "Args": [
                    "-h",
                    "aaa",
                    "-p",
                    "6666",
                    "-d",
                    "aa",
                    "-u",
                    "aa",
                    "-pw",
                    "aa",
                    "-t",
                    "aa",
                    "-r",
                    "aa"
                ],
                "Privileges": {
                    "CredentialSpec": null,
                    "SELinuxContext": null
                },
                "Hosts": [
                    "127.0.0.1 localhost"
                ],
                "Secrets": [
                    {
                        "File": {
                            "Name": "aaa",
                            "UID": "0",
                            "GID": "0",
                            "Mode": 292
                        },
                        "SecretID": "aaa",
                        "SecretName": "aaa"
                    }
                ],
                "Isolation": "default"
            },
            "Resources": {
                "Limits": {
                    "NanoCPUs": 14000000000
                },
                "Reservations": {
                    "NanoCPUs": 14000000000
                }
            },
            "RestartPolicy": {
                "Condition": "none",
                "MaxAttempts": 0
            },
            "Placement": {
                "Constraints": [
                    "node.role == manager"
                ],
                "Platforms": [
                    {
                        "Architecture": "amd64",
                        "OS": "linux"
                    }
                ]
            },
            "Networks": [
                {
                    "Target": "xgkebiqoh7rhb27irhgr7dnev"
                }
            ],
            "ForceUpdate": 0
        },
        "ServiceID": "4kb4zu9du8b0pui4lyt820gia",
        "Slot": 1,
        "NodeID": "o6lvbcj08gbweofyg6hjzysgx",
        "Status": {
            "Timestamp": "2021-07-09T17:35:00.3918131Z",
            "State": "failed",
            "Message": "started",
            "Err": "task: non-zero exit (1)",
            "ContainerStatus": {
                "ContainerID": "ee2cfb7ebcf80298238ff41af8871529cc494af223054cd43233640ec02e245f",
                "PID": 0,
                "ExitCode": 1
            },
            "PortStatus": {}
        },
        "DesiredState": "shutdown",
        "NetworksAttachments": [
            {
                "Network": {
                    "ID": "xgkebiqoh7rhb27irhgr7dnev",
                    "Version": {
                        "Index": 2916
                    },
                    "CreatedAt": "2021-03-30T11:42:28.9523662Z",
                    "UpdatedAt": "2021-07-09T09:41:36.1615405Z",
                    "Spec": {
                        "Name": "host",
                        "Labels": {
                            "com.docker.swarm.predefined": "true"
                        },
                        "DriverConfiguration": {
                            "Name": "host"
                        },
                        "Scope": "swarm"
                    },
                    "DriverState": {
                        "Name": "host"
                    },
                    "IPAMOptions": {
                        "Driver": {}
                    }
                }
            }
        ]
    }
]
```

**Comment by gabrieldemarmiesse** [comment]
Thank you for the great bug report, I'll take a look tonight and make a bugfix release as this is a very small bug (even if I agree that this must be blocking for some of your work)

**Comment by gabrieldemarmiesse** [comment]
https://github.com/gabrieldemarmiesse/python-on-whales/pull/203 should have fixed your issue, I'll make a release soon so that you can try it :)

**Comment by gabrieldemarmiesse** [comment]
The release it out. 0.21.1. Could you do `pip install --upgrade python-on-whales` and tell me if it works? Thanks

**Comment by gabrieldemarmiesse** [comment]
Since I didn't get any answer, I'll assume this is working for you. Thank you for the bug report!

**Comment by BWibo** [comment]
Tested a minute ago and it is working. Thx for the quick fix!

**Comment by gabrieldemarmiesse** [comment]
Nice, I'm glad to hear that, have a great day :)
