### ISSUE TITLE
it forces me to download docker client binary file on windows

### ISSUE THREAD

**Issue by Smyja** [gabrieldemarmiesse/python-on-whales#225]
I ran this code.
```
from python_on_whales import DockerClient
docker = DockerClient(host="ssh://root@xx.xxx.xx.xx")
docker.ps()
```
and it suddenly started downloading docker and to make it worse, it crashed. i have downloaded this 3 times. Also, i ran the equivalent for this with docker-py and it worked perfectly. i am using windows.

```
C:/Users/USER/AppData/Local/Programs/Python/Python37/python.exe c:/Users/USER/Desktop/cvbn/eyede
/pywale.py
C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\python_on_whales\client_config.py:65: UserWarning: The docker client binary file was not found on your system.
Docker on whales will try to download it for you.
Don't worry, it won't be in the PATH and won't have anything to do with the package manager of your system.
Note: We are not installing the docker daemon, which is a lot heavier and harder to install. We're just downloading a single standalone binary file.
If you want to trigger the download of the client binary file manually (for example if you want to do it in a Dockerfile), you can run the following command:
 $ python-on-whales download-cli

  "The docker client binary file was not found on your system. \n"
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 65.4M/65.4M [00:25<00:00, 2.53MiB/s]
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 932, in _unpack_tarfile
    tarobj = tarfile.open(filename)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 1578, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/USER/Desktop/cvbn/eyede/pywale.py", line 4, in <module>
    docker.ps()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\python_on_whales\components\container\cli_wrapper.py", line 947,
in list
    full_cmd = self.docker_cmd
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\python_on_whales\client_config.py", line 134, in docker_cmd
    return self.client_config.docker_cmd
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\python_on_whales\client_config.py", line 85, in docker_cmd
    result = Command([self.get_docker_path()])
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\python_on_whales\client_config.py", line 78, in get_docker_path
    download_docker_cli()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\python_on_whales\download_binaries.py", line 39, in download_docker_cli
    shutil.unpack_archive(str(tar_file), str(extract_dir))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 1002, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 935, in _unpack_tarfile
    "%s is not a compressed or uncompressed tar file" % filename)
shutil.ReadError: C:\Users\USER\AppData\Local\Temp\tmpv86v5tuj\docker.tgz is not a compressed or uncompressed tar file
```

**Comment by gabrieldemarmiesse** [comment]
Thank you for the great bug report! I believe I know what is going on. Fetching the docker binary is quite different in windows and it doesn't come in a tar. I believe we need a switch. I'll take a look at this bug, I'll try the fix on my windows PC
