### ISSUE TITLE
Docker container list error

### ISSUE THREAD

**Issue by Smyja** [gabrieldemarmiesse/python-on-whales#241]
When i try to get the list of containers in my docker on my widows using the latest python_on_whales
```
from python_on_whales import DockerClient
docker = DockerClient(host="ssh://root@xx.xx.xx")
docker.container.list(all=True)
```

i get this error```

Traceback (most recent call last):
  File "pywale.py", line 3, in <module>
    docker.container.list(all=True)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\python_on_whales\components\container\cli_wrapper.py", line 955,
in list
    for x in run(full_cmd).splitlines()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\python_on_whales\utils.py", line 149, in run
    completed_process.stderr,
python_on_whales.exceptions.DockerException: The docker command executed was `C:\Users\USER\.cache\python-on-whales\docker-cli\20.10.5\docker --host ssh://root@xxx.xx.xx.xx container list -q --no-trunc --all`.
It returned with code 2
The content of stdout is ''
The content of stderr is 'panic: Invalid standard handle identifier: 4294967286

goroutine 1 [running]:
github.com/docker/cli/vendor/github.com/Azure/go-ansiterm/winterm.GetStdFile(0xfffffff6, 0x2f4, 0xc0004a5dec)
        C:/gopath/src/github.com/docker/cli/vendor/github.com/Azure/go-ansiterm/winterm/ansi.go:173 +0x1f3
github.com/docker/cli/vendor/github.com/moby/term/windows.NewAnsiReader(0xfffffff6, 0xc0004a5dec, 0x20d5a60)
        C:/gopath/src/github.com/docker/cli/vendor/github.com/moby/term/windows/ansi_reader.go:34 +0x36
github.com/docker/cli/vendor/github.com/moby/term.StdStreams(0xc0003e36c0, 0xc0004a5eb8, 0x1, 0x1, 0x0, 0x0)
        C:/gopath/src/github.com/docker/cli/vendor/github.com/moby/term/term_windows.go:75 +0x1eb
github.com/docker/cli/cli/command.NewDockerCli(0x0, 0x0, 0x0, 0x19ba60c, 0x1b500e0, 0xc0002421b0)
        C:/gopath/src/github.com/docker/cli/cli/command/cli.go:473 +0x1a7
main.main()
        C:/gopath/src/github.com/docker/cli/cmd/docker/docker.go:291 +0x4b
```
'

**Comment by gabrieldemarmiesse** [comment]
Thanks for the bug report! Sounds like a go panic issue.

Could you try:

```
docker --host ssh://root@xxx.xx.xx.xx container list -q --no-trunc --all
```
from the command line and tell me if you have the same error? If so please open a bug report in the docker repository. This is a go panic and should be solved at the docker level, not the python-on-whales level.

Whatever happends, the go client should never panic, even if the inputs are wrong. It should ouput a human readable error message. And it's not the case here.

**Comment by gabrieldemarmiesse** [comment]
Closing this issue due to inactivity
