### ISSUE TITLE
Error related to Windows path for volume

### ISSUE THREAD

**Issue by TracyWel** [gabrieldemarmiesse/python-on-whales#331]
Hello,
I really appreciate this package. Thanks for putting it out there! I'm having trouble running the code below. The error messaging indicates it has to do with what is in the win_path variable, namely "invalid mode". See error messages below in both detached=False and =True.

```python
def agl_docker_start(win_path, docker_path):
    from python_on_whales import docker
    print(win_path, docker_path)
    docker.run(
        "agl_image",
        name="agl_container",
        volumes=[(win_path, docker_path)],
        detach=False,
    )
```

I’ve tried win_path values of (as a string):
c:\Users\TracyTD\ShareData
C:\Users\TracyTD\ShareData
c:\\Users\\TracyTD\\ShareData
c:/Users/TracyTD/ShareData

I have also  successfully run this image/container on the command line with:
```
docker run -it -v c:\Users\TracyTD\ShareData:/tmp/shareddata agl_image
```
**This 
"Error response from daemon: invalid mode: \Users\TracyTD\ShareData."
makes me wonder if Windows is not supported, since the drive letter is missing.**

```
/tmp/shareddata c:\Users\TracyTD\ShareData
docker: Error response from daemon: invalid mode: \Users\TracyTD\ShareData.
See 'docker run --help'.
Traceback (most recent call last):
  File "C:\Users\TracyTD\OneDrive - Truth Data Insights\TD\Software\AGL\AGL\g1000_preprocessing.py", line 329, in <module>
    main(sys.argv[1:])  # command line
  File "C:\Users\TracyTD\OneDrive - Truth Data Insights\TD\Software\AGL\AGL\g1000_preprocessing.py", line 277, in main
    agl_docker_start(docker_input_path, input_path)
  File "C:\Users\TracyTD\OneDrive - Truth Data Insights\TD\Software\AGL\AGL\agl_main.py", line 395, in agl_docker_start
    docker.run(
  File "C:\Users\TracyTD\AppData\Local\Programs\Python\Python39\lib\site-packages\python_on_whales\components\container\cli_wrapper.py", line 1554, in run
    return run(full_cmd, tty=tty, capture_stderr=False)
  File "C:\Users\TracyTD\AppData\Local\Programs\Python\Python39\lib\site-packages\python_on_whales\utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `C:\Program Files\Docker\Docker\resources\bin\docker.EXE container run --name agl_container --volume /tmp/shareddata:c:\Users\TracyTD\ShareData agl_image`.
It returned with code 125
The content of stdout is ''
The content of stderr can be found above the stacktrace (it wasn't captured).
```

Here’s the output with detach=True

```
/tmp/shareddata c:\Users\TracyTD\ShareData
Traceback (most recent call last):
  File "C:\Users\TracyTD\OneDrive - Truth Data Insights\TD\Software\AGL\AGL\g1000_preprocessing.py", line 329, in <module>
    main(sys.argv[1:])  # command line
  File "C:\Users\TracyTD\OneDrive - Truth Data Insights\TD\Software\AGL\AGL\g1000_preprocessing.py", line 277, in main
    agl_docker_start(docker_input_path, input_path)
  File "C:\Users\TracyTD\OneDrive - Truth Data Insights\TD\Software\AGL\AGL\agl_main.py", line 395, in agl_docker_start
    docker.run(
  File "C:\Users\TracyTD\AppData\Local\Programs\Python\Python39\lib\site-packages\python_on_whales\components\container\cli_wrapper.py", line 1550, in run
    return Container(self.client_config, run(full_cmd))
  File "C:\Users\TracyTD\AppData\Local\Programs\Python\Python39\lib\site-packages\python_on_whales\utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `C:\Program Files\Docker\Docker\resources\bin\docker.EXE container run --detach --name agl_container --volume /tmp/shareddata:c:\Users\TracyTD\ShareData agl_image`.
It returned with code 125
The content of stdout is ''
The content of stderr is 'docker: Error response from daemon: invalid mode: \Users\TracyTD\ShareData.
See 'docker run --help'.
```

**Comment by gabrieldemarmiesse** [comment]
I believe this issue is related to the interaction between docker and windows, and unrelated to python-on-whales.

When you use the -v option in docker run, you have multiple syntax possible

```
-v /path/in/host:/path/in/container
-v /path/in/host:/path/in/container:mode  (for example /tmp/something:/tmp/other:ro for read only)
```
docker is interpreting the `:` after the `c` as the separator between paths or between the path and the mode.

I wonder if you can do like in linux `/c/Users/TracyTD/ShareData:/tmp/shareddata` or `c/Users/TracyTD/ShareData:/tmp/shareddata`.
I believe you'll have less issues.

**Comment by gabrieldemarmiesse** [comment]
Also I see 
```
docker.EXE container run --detach --name agl_container --volume /tmp/shareddata:c:\Users\TracyTD\ShareData
```
It seems that the paths in the container and in windows are inverted. Did you inverted the win_path and docker_path by any chance in your code?

**Comment by TracyWel** [comment]
That was it! Thank you so much for the help
