### ISSUE TITLE
Support podman parsing

### ISSUE THREAD

**Issue by pyhedgehog** [gabrieldemarmiesse/python-on-whales#334]
```Python console
>>> podman=python_on_whales.DockerClient(client_binary='podman')
>>> podman.container.inspect('176579f64e64a8fc7c0f29250301a88977c3583204b0f7a0a080dbf8ea53154f')                                     [648/1832]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/python_on_whales/client_config.py", line 242, in _fetch_and_parse_inspect_result
    return self._parse_json_object(json_object)
  File "/usr/lib/python3.9/site-packages/python_on_whales/components/container/cli_wrapper.py", line 60, in _parse_json_object
    return ContainerInspectResult.parse_obj(json_object)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ContainerInspectResult
Config -> Entrypoint
  value is not a valid list (type=type_error.list)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/python_on_whales/components/container/cli_wrapper.py", line 880, in inspect
    return Container(self.client_config, x)
  File "/usr/lib/python3.9/site-packages/python_on_whales/components/container/cli_wrapper.py", line 44, in __init__
    super().__init__(client_config, "id", reference, is_immutable_id)
  File "/usr/lib/python3.9/site-packages/python_on_whales/client_config.py", line 184, in __init__
    self._fetch_and_parse_inspect_result(reference_or_id)
  File "/usr/lib/python3.9/site-packages/python_on_whales/client_config.py", line 248, in _fetch_and_parse_inspect_result
    raise ParsingError(
python_on_whales.client_config.ParsingError: There was an error parsing the json response from the Docker daemon.
This is a bug with python-on-whales itself. Please head to
https://github.com/gabrieldemarmiesse/python-on-whales/issues
and open an issue. You should copy this error message and
the json response from the Docker daemon. The json response was put
in /tmp/tmp7runnyta.json because it's a bit too big to be printed
on the screen. Make sure that there are no sensitive data in the
json file before copying it in the github issue.
>>> o=json.loads(pathlib.Path('/tmp/tmp7runnyta.json').read_text())
>>> o[0]['Config']['Entrypoint']
''
````

Workaround **for exactly this problem**:
```python
mf = python_on_whales.components.container.models.ContainerConfig.__fields__['entrypoint']
mf2 = pydantic.fields.ModelField.infer(
    name=mf.name,
    value=None,
    annotation=typing.Union[typing.List[str], str],
    class_validators=mf.class_validators,
    config=mf.model_config)
for k in mf.__slots__:
    setattr(mf, k, getattr(mf2, k))
```

**Comment by pyhedgehog** [comment]
Note, that there can be more model differences not caught by me.
Sorry for this.

**Comment by gabrieldemarmiesse** [comment]
No worries, it's hard to always parse the right thing since there isn't much documentation for docker/podman json models. I fixed it in https://github.com/gabrieldemarmiesse/python-on-whales/pull/336
