### ISSUE TITLE
import python_on_whales fails 'NetworkIPAM' has no attribute '__fields__'

### ISSUE THREAD

**Issue by dand-oss** [gabrieldemarmiesse/python-on-whales#429]
python --version
Python 3.10.10

Successfully installed python-on-whales-0.60.0

python -c 'import python_on_whales'

`
/t/pyenv/versions/py-default/lib/python3.10/site-packages/pydantic/config.py:123: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/t/pyenv/versions/py-default/lib/python3.10/site-packages/python_on_whales/__init__.py", line 2, in <module>
    from .components.buildx.cli_wrapper import Builder
  File "/t/pyenv/versions/py-default/lib/python3.10/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 9, in <module>
    import python_on_whales.components.image.cli_wrapper
  File "/t/pyenv/versions/py-default/lib/python3.10/site-packages/python_on_whales/components/image/cli_wrapper.py", line 16, in <module>
    from python_on_whales.components.container.cli_wrapper import (
  File "/t/pyenv/versions/py-default/lib/python3.10/site-packages/python_on_whales/components/container/cli_wrapper.py", line 12, in <module>
    import python_on_whales.components.network.cli_wrapper
  File "/t/pyenv/versions/py-default/lib/python3.10/site-packages/python_on_whales/components/network/cli_wrapper.py", line 12, in <module>
    from python_on_whales.components.network.models import (
  File "/t/pyenv/versions/py-default/lib/python3.10/site-packages/python_on_whales/components/network/models.py", line 8, in <module>
    class NetworkIPAM(DockerCamelModel):
  File "/t/pyenv/versions/py-default/lib/python3.10/site-packages/python_on_whales/utils.py", line 298, in all_fields_optional
    for field in cls.__fields__.values():
AttributeError: type object 'NetworkIPAM' has no attribute '__fields__'. Did you mean: '__fields_set__'?
`

**Comment by dev-isaac** [comment]
@dand-oss 
Hi, I'm not a contributor, but just dropping by to share my experience with this same error.

We traced this issue to a new pydantic release: https://github.com/pydantic/pydantic/releases/tag/v2.0a1

We fixed it by specifying the version of the pydantic installation: `pydantic==1.10.5`
Other pydantic versions may also work, but we haven't tested them ourselves.

Hope it helps!

**Comment by gabrieldemarmiesse** [comment]
Indeed I think we should make a fix for this issue that would allow python-on-whales to work with any version of pydantic. That should be possible by checking the version of pydantic at runtime
