### ISSUE TITLE
Does not build any images

### ISSUE THREAD

**Issue by mgzenitech** [gabrieldemarmiesse/python-on-whales#436]
```
Traceback (most recent call last):
  File "<stdin>", line 39, in <module>
  File "/home/marius/Documents/Projects/docker-internal-images/.venv/lib/python3.10/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 587, in stream_buildx_logs
    for origin, value in stream_stdout_and_stderr(full_cmd, env=env):
  File "/home/marius/Documents/Projects/docker-internal-images/.venv/lib/python3.10/site-packages/python_on_whales/utils.py", line 264, in stream_stdout_and_stderr
    raise DockerException(full_cmd, exit_code, stderr=full_stderr)
python_on_whales.exceptions.DockerException: The docker command executed was `/home/marius/.cache/python-on-whales/docker-cli/20.10.5/docker buildx build --build-arg REGISTRY=localhost --build-arg VERSION=3.17.3 --label based-on=Alpine --label size-optimized=1 --file images/base/Dockerfile --cache-from localhost/base:v --tag v3.17.3 images/base`.
It returned with code 125
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr is 'unknown flag: --build-arg
See 'docker --help'.
```

Podman installed on my system with `alias docker=podman` if that helps or is related to the issue

**Comment by mgzenitech** [comment]
Erm, looks like I've had to specifiy podman :)

**Comment by mgzenitech** [comment]
Just tried with alpine image in the bitbucket pipeline with Docker installed and still get same issue (although locally with `client_call = ["podman"]` set everything works):
```
Traceback (most recent call last):
  File "<stdin>", line 39, in <module>
  File "/app/.venv/lib/python3.10/site-packages/lib/utils/docker/build_image.py", line 29, in build_image
    for output_line in docker.build(
  File "/app/.venv/lib/python3.10/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 587, in stream_buildx_logs
    for origin, value in stream_stdout_and_stderr(full_cmd, env=env):
  File "/app/.venv/lib/python3.10/site-packages/python_on_whales/utils.py", line 264, in stream_stdout_and_stderr
    raise DockerException(full_cmd, exit_code, stderr=full_stderr)
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker buildx build --build-arg REGISTRY=363873133158.dkr.ecr.eu-west-2.amazonaws.com --build-arg VERSION=3.17.3 --label based-on=Alpine --label size-optimized=1 --pull --file images/base/Dockerfile --cache-from 363873133158.dkr.ecr.eu-west-2.amazonaws.com/base --tag 363873133158.dkr.ecr.eu-west-2.amazonaws.com/base:v3.17.3 --tag 363873133158.dkr.ecr.eu-west-2.amazonaws.com/base:latest images/base`.
It returned with code 125
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr is 'unknown flag: --build-arg
See 'docker --help'.
```

**Comment by mgzenitech** [comment]
Apparently for alpine you have to separately install `docker-cli-buildx` so this issue finally can be closed.
