### ISSUE TITLE
disable privileged on build

### ISSUE THREAD

**Issue by mgzenitech** [gabrieldemarmiesse/python-on-whales#438]
```
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 4.7s done
#1 creating container buildx_buildkit_default 0.0s done
#1 ERROR: Error response from daemon: authorization denied by plugin pipelines: --privileged=true is not allowed
------
> [internal] booting buildkit:
------
ERROR: Error response from daemon: authorization denied by plugin pipelines: --privileged=true is not allowed
Traceback (most recent call last):
  File "<stdin>", line 39, in <module>
  File "/opt/atlassian/pipelines/agent/build/.venv/lib/python3.10/site-packages/lib/utils/docker/build_image.py", line 29, in build_image
    for output_line in docker.build(
  File "/opt/atlassian/pipelines/agent/build/.venv/lib/python3.10/site-packages/python_on_whales/components/buildx/cli_wrapper.py", line 587, in stream_buildx_logs
    for origin, value in stream_stdout_and_stderr(full_cmd, env=env):
  File "/opt/atlassian/pipelines/agent/build/.venv/lib/python3.10/site-packages/python_on_whales/utils.py", line 264, in stream_stdout_and_stderr
    raise DockerException(full_cmd, exit_code, stderr=full_stderr)
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker buildx build --build-arg REGISTRY=363873133158.dkr.ecr.eu-west-2.amazonaws.com --build-arg VERSION=3.17.3 --label based-on=Alpine --label size-optimized=1 --pull --file images/base/Dockerfile --cache-from 363873133158.dkr.ecr.eu-west-2.amazonaws.com/base --tag 363873133158.dkr.ecr.eu-west-2.amazonaws.com/base:v3.17.3 --tag 363873133158.dkr.ecr.eu-west-2.amazonaws.com/base:latest images/base`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr is 'WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 4.7s done
#1 creating container buildx_buildkit_default 0.0s done
#1 ERROR: Error response from daemon: authorization denied by plugin pipelines: --privileged=true is not allowed
------
 > [internal] booting buildkit:
------
ERROR: Error response from daemon: authorization denied by plugin pipelines: --privileged=true is not allowed
```

In bitbucket pipelines buildkit is enabled with env var `export DOCKER_BUILDKIT=1` (https://support.atlassian.com/bitbucket-cloud/docs/run-docker-commands-in-bitbucket-pipelines/#Enable-Docker-BuildKit), however they do not allow privileged mode. How would I disable it so that the image building process would work in the pipeline?

**Comment by mgzenitech** [comment]
It is extremely weird as I'm not setting anything privileged related for build:
```
    for output_line in docker.build(
        context_path = dockerfile.parent,
        build_args = arguments if arguments else {},
        cache = True,
        cache_from = name if not name.startswith("localhost") else None,
        file = dockerfile,
        labels = {"based-on": "Alpine", "size-optimized": "1"},
        pull = not name.startswith("localhost"),
        tags = tags_complete,
        target = target,
        stream_logs = True
    ):
        if not hide_output:
            print(output_line.strip())
```

**Comment by gabrieldemarmiesse** [comment]
Hi! Can you try to execute the build command from the command line, outside python? I suspect that the problem is with the buildkit install and not wity python-on-whales

**Comment by gabrieldemarmiesse** [comment]
It seems the command is slightly different. Python-on-whales does "docker buildx build" and I believe that's the issue here. Now the question is why bit bucket pipeline doesn't allow users to use docker buildx build instead of docker build... That I don't know. Docker buildx build is a valid docker command so I would argue that the issue is with bit bucket, not python-on-whales

**Comment by mgzenitech** [comment]
@gabrieldemarmiesse is it possible to change path to `docker` binary that Python-on-whales detects automatically? I could probably create a shell script with shebang

**Comment by gabrieldemarmiesse** [comment]
It's possible indeed! Refer to this page: https://gabrieldemarmiesse.github.io/python-on-whales/docker_client/

Look at the argument "docker_call"

**Comment by mgzenitech** [comment]
Looks like my hack worked... Didn't need to change `docker_call` as that would affect also users working locally :)

```
cat << 'EOF' >> /usr/local/bin/docker
#!/usr/bin/env bash

arguments=($@)
if [[ "${arguments[0]}" == buildx ]] && [[ "${arguments[1]}" == build ]]; then
  arguments[0]=
fi
/usr/bin/docker ${arguments[@]}
EOF
chmod +x /usr/local/bin/docker
```

Will do more tests and give feedback here.

**Comment by mgzenitech** [comment]
Yep, looks like everything works as expected with my hack :) Gonna close this issue. Thanks!

**Comment by gabrieldemarmiesse** [comment]
I'm happy to help!
